services:
  db:
    image: pgvector/pgvector:pg18
    restart: unless-stopped
    environment:
      POSTGRES_DB: case_tasks_db
      POSTGRES_USER: case_app
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql
      - ./db/init.sql:/docker-entrypoint-initdb.d/01-init.sql:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U case_app -d case_tasks_db"]
      interval: 5s
      timeout: 5s
      retries: 10

  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    restart: unless-stopped
    volumes:
      - ollama_data:/root/.ollama

  frontend:
    build:
      context: ./CRUD_CT_FE
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "8080:80"
    depends_on:
      - backend
    restart: unless-stopped

  backend:
    build:
      context: ./CRUD_CT_BE
    restart: unless-stopped
    environment:
      PORT: 3000
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: case_tasks_db
      DB_USER: case_app
      DB_PASSWORD: ${DB_PASSWORD}
      OLLAMA_HOST: http://ollama:11434
    depends_on:
      db:
        condition: service_healthy
      ollama:
        condition: service_started
    ports:
      - "127.0.0.1:3000:3000"

volumes:
  postgres_data:
  ollama_data: